all: test

test:
	go test ./...

chrome: # Run Chrome timing tests
	go test -tags chrome ./...

.PHONY: resources
resources:
	echo "//Autogenerated by make resources\npackage mermaid\n\nconst mermaidjs64 =\`\n" > mermaid/mermaid.min.js.go
	cat resources/mermaid.min.js | base64 >> mermaid/mermaid.min.js.go
	echo "\`" >> mermaid/mermaid.min.js.go
